name: publish to pypi

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build
        run: |
          pip install hatch
          hatch build

      - name: Publish distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: hatch publish -u __token__

      - name: Publish distribution to Test PyPI
        env:
          HATCH_INDEX_AUTH: ${{ secrets.TEST_PYPI_TOKEN }}
        run: hatch publish -u __token__ -r test
