name: publish to pypi

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build
        run: |
          pip install hatch
          hatch build

      - name: Publish distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: hatch publish -a "$SECRET"
        env:
          SECRET: ${{ secrets.PYPI_TOKEN }}

      - name: Publish distribution to Test PyPI
        run: hatch publish -r test -a "$SECRET"
        env:
          SECRET: ${{ secrets.TEST_PYPI_TOKEN }}