name: pytest

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]
    if: "!(contains(github.repository, 'template') || contains(github.event.head_commit.message, 'initial commit'))"

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: test
        run: |
          pip install hatch
          hatch run tests:pytest
